[project]
name = "affmap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.0",
    "pydantic>=2.10.3",
    "pytest>=8.3.4",
]
